### ISSUE TITLE
Tests on Travis CI fail with s3

### ISSUE THREAD

**Issue by piotrrojek** [graymeta/stow#98]
Connection issue? Confirmed with @Xercoy, fails every time.

```
=== RUN   TestStow
SIGQUIT: quit
PC=0x457461 m=0
goroutine 0 [idle]:
runtime.futex(0x91ae10, 0x0, 0x0, 0x0, 0x7fff00000000, 0x42295e, 0x0, 0x0, 0x7fffc4361de8, 0x40eefb, ...)
    /home/travis/.gimme/versions/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0x91ae10, 0x7fff00000000, 0xffffffffffffffff)
    /home/travis/.gimme/versions/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x91ae10)
    /home/travis/.gimme/versions/go/src/runtime/lock_futex.go:145 +0x6b
runtime.stopm()
    /home/travis/.gimme/versions/go/src/runtime/proc.go:1617 +0xad
runtime.findrunnable(0xc420023300, 0x0)
    /home/travis/.gimme/versions/go/src/runtime/proc.go:2049 +0x241
runtime.schedule()
    /home/travis/.gimme/versions/go/src/runtime/proc.go:2148 +0x14c
runtime.park_m(0xc4200d21a0)
    /home/travis/.gimme/versions/go/src/runtime/proc.go:2211 +0xa0
runtime.mcall(0x7fffc4361f70)
    /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:240 +0x5b
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc4200d60c0, 0x783003, 0x8, 0x796188, 0xc42012fcf0)
    /home/travis/.gimme/versions/go/src/testing/testing.go:675 +0x2ea
testing.runTests.func1(0xc4200d60c0)
    /home/travis/.gimme/versions/go/src/testing/testing.go:830 +0x67
testing.tRunner(0xc4200d60c0, 0xc42012fdb0)
    /home/travis/.gimme/versions/go/src/testing/testing.go:637 +0x81
testing.runTests(0x796200, 0x9161a0, 0x4, 0x4, 0xc42012fe48)
    /home/travis/.gimme/versions/go/src/testing/testing.go:836 +0x299
testing.(*M).Run(0xc42054cef8, 0xc4200c2e20)
    /home/travis/.gimme/versions/go/src/testing/testing.go:771 +0x90
main.main()
    github.com/graymeta/stow/s3/_test/_testmain.go:60 +0xc6
goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
    /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:2160 +0x1
goroutine 5 [IO wait]:
net.runtime_pollWait(0x7fcaed978fc8, 0x72, 0x3)
    /home/travis/.gimme/versions/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42020daa8, 0x72, 0x8ebba0, 0x8e8458)
    /home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42020daa8, 0xc420100000, 0x1000)
    /home/travis/.gimme/versions/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42020da40, 0xc420100000, 0x1000, 0x1000, 0x0, 0x8ebba0, 0x8e8458)
    /home/travis/.gimme/versions/go/src/net/fd_unix.go:246 +0x181
net.(*conn).Read(0xc420190150, 0xc420100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/net/net.go:176 +0x70
crypto/tls.(*block).readFromUntil(0xc420330ab0, 0x7fcaed9300c8, 0xc420190150, 0x5, 0xc420190150, 0x0)
    /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:481 +0x91
crypto/tls.(*Conn).readRecord(0xc4202d9500, 0x796a17, 0xc4202d9608, 0x0)
    /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:583 +0xc4
crypto/tls.(*Conn).Read(0xc4202d9500, 0xc420101000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1120 +0x116
net/http.(*persistConn).Read(0xc420089200, 0xc420101000, 0x1000, 0x1000, 0x8f, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/net/http/transport.go:1292 +0x14b
bufio.(*Reader).fill(0xc4201feba0)
    /home/travis/.gimme/versions/go/src/bufio/bufio.go:97 +0x10b
bufio.(*Reader).ReadSlice(0xc4201feba0, 0xc42038460a, 0x2, 0x2, 0x2, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/bufio/bufio.go:338 +0xb5
net/http/internal.readChunkLine(0xc4201feba0, 0xc4201feba0, 0xc4203846b0, 0x2, 0x2, 0x2)
    /home/travis/.gimme/versions/go/src/net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc420384690)
    /home/travis/.gimme/versions/go/src/net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc420384690, 0xc420274689, 0x577, 0x577, 0xc420544f40, 0xc420274600, 0x60b3b6)
    /home/travis/.gimme/versions/go/src/net/http/internal/chunked.go:93 +0x11d
net/http.(*body).readLocked(0xc4203e9c80, 0xc420274689, 0x577, 0x577, 0xc4205352c8, 0x42923d, 0x795c30)
    /home/travis/.gimme/versions/go/src/net/http/transfer.go:648 +0x61
net/http.(*body).Read(0xc4203e9c80, 0xc420274689, 0x577, 0x577, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/net/http/transfer.go:640 +0xf6
net/http.(*bodyEOFSignal).Read(0xc4203e9d00, 0xc420274689, 0x577, 0x577, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/net/http/transport.go:2011 +0xe9
bytes.(*Buffer).ReadFrom(0xc4205353b8, 0x8ea3e0, 0xc4203e9d00, 0xc4203f4000, 0x0, 0x200)
    /home/travis/.gimme/versions/go/src/bytes/buffer.go:179 +0x155
io/ioutil.readAll(0x8ea3e0, 0xc4203e9d00, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/travis/.gimme/versions/go/src/io/ioutil/ioutil.go:33 +0x150
io/ioutil.ReadAll(0x8ea3e0, 0xc4203e9d00, 0xc4203e9d00, 0x8ea3e0, 0xc4203e9d00, 0xc4200300c0, 0x199)
    /home/travis/.gimme/versions/go/src/io/ioutil/ioutil.go:42 +0x3e
github.com/aws/aws-sdk-go/service/s3.buildGetBucketLocation(0xc4201bea80)
    /home/travis/gopath/src/github.com/aws/aws-sdk-go/service/s3/bucket_location.go:18 +0xb9
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc4201bec30, 0xc4201bea80)
    /home/travis/gopath/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0x87
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc4201bea80, 0xc4200300b8, 0xc4201bea80)
    /home/travis/gopath/src/github.com/aws/aws-sdk-go/aws/request/request.go:318 +0x463
github.com/aws/aws-sdk-go/service/s3.(*S3).GetBucketLocation(0xc420030098, 0xc4200300b8, 0x0, 0x0, 0x1)
    /home/travis/gopath/src/github.com/aws/aws-sdk-go/service/s3/api.go:1244 +0x4d
github.com/graymeta/stow/s3.(*location).Containers(0xc4200c3160, 0x0, 0x0, 0x0, 0x0, 0x64, 0xc420331f80, 0x7fcaed9d0000, 0x0, 0x71d9e0, ...)
    /home/travis/gopath/src/github.com/graymeta/stow/s3/location.go:70 +0x14f
github.com/graymeta/stow.WalkContainers(0x8efe60, 0xc4200c3160, 0x0, 0x0, 0x64, 0xc42018d100, 0x8e9d20, 0xc4203cda00)
    /home/travis/gopath/src/github.com/graymeta/stow/walk.go:63 +0x88
github.com/graymeta/stow/test.All(0xc4200d6180, 0x78166d, 0x2, 0x8eb420, 0xc420015800)
    /home/travis/gopath/src/github.com/graymeta/stow/test/test.go:238 +0x4569
github.com/graymeta/stow/s3.TestStow(0xc4200d6180)
    /home/travis/gopath/src/github.com/graymeta/stow/s3/stow_test.go:20 +0x109
testing.tRunner(0xc4200d6180, 0x796188)
    /home/travis/.gimme/versions/go/src/testing/testing.go:637 +0x81
created by testing.(*T).Run
    /home/travis/.gimme/versions/go/src/testing/testing.go:674 +0x2c0
goroutine 467 [select]:
net/http.(*persistConn).writeLoop(0xc420089200)
    /home/travis/.gimme/versions/go/src/net/http/transport.go:1680 +0x3b4
created by net/http.(*Transport).dialConn
    /home/travis/.gimme/versions/go/src/net/http/transport.go:1094 +0x7e2
goroutine 466 [select]:
net/http.(*persistConn).readLoop(0xc420089200)
    /home/travis/.gimme/versions/go/src/net/http/transport.go:1575 +0x9dc
created by net/http.(*Transport).dialConn
    /home/travis/.gimme/versions/go/src/net/http/transport.go:1093 +0x7bd
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x91ae10
rsi    0x0
rbp    0x7fffc4361db8
rsp    0x7fffc4361d70
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc4201feca8
r13    0x0
r14    0xc4201fec60
r15    0x0
rip    0x457461
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL    github.com/graymeta/stow/s3 600.005s
```

**Comment by matryer** [comment]
@jasonhancock does this make Travis useless for Stow?
